feature-loginPageHeader
aemsites/hdfc-bank pull request #146
Opened 2024-04-16 07:59 UTC by satyajeetdhere7444

Test URLs:

- https://feature-loginPageHeader--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc

2024-04-16 08:05 UTC, kunal-adobe approved these changes

2024-04-17 07:42 UTC, srivastava21ashish requested changes

2024-04-17 07:42 UTC, srivastava21ashish commented on styles/header-banner.css
>  }
EOL missing

2024-04-17 07:42 UTC, srivastava21ashish commented on styles/header-banner.css
>      background: var(--color-interface-background-tertiary);
have to imported this file somewhere?

2024-04-17 08:44 UTC, satyajeetdhere7444 commented on styles/header-banner.css
>      background: var(--color-interface-background-tertiary);
yes, this var declare in **color-palette.css** and it imported in styles.css, we are imporating all css file styles.css

2024-04-17 08:55 UTC, satyajeetdhere7444 commented on styles/header-banner.css
>  }
it didn't show the lint issue

2024-04-17 09:04 UTC, merged