Feature pan validation
aemsites/hdfc-bank pull request #147
Opened 2024-04-16 11:17 UTC by kunal-adobe

Test URLs:

- https://feature-pan-validation--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc

2024-04-16 12:37 UTC, BazilMuralidharan approved these changes

2024-04-17 07:40 UTC, srivastava21ashish requested changes

2024-04-17 07:40 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +    if (CUSTOMER_INPUT.mobileNumber) {
Unecessary cyclometic complexity added. This is not a condition but a switch

2024-04-17 07:40 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +  } else if (CUSTOMER_INPUT.mobileNumber) {
what are we doing here?

2024-04-17 07:40 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +        const errorCode = 'INVALID_INPUT_PAN_REQUEST';
where are we using this constant?

2024-04-17 07:40 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +      } catch (errObj) {
arrow function please!

2024-04-17 07:40 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +    handlePanFailure(errorObj) {
Proper nomencalture please! This error object name doesn't tell anything about what this error is. 
Likewise on overall file changes

2024-04-22 05:38 UTC, srivastava21ashish approved these changes

2024-04-22 05:38 UTC, merged