Move code to mappings
aemsites/hdfc-bank pull request #164
Opened 2024-04-25 07:48 UTC by suparnabose373

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #
Test URLs:
Before: https://main--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc
After: https://bugfix-check-offers-CTA--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc

2024-04-25 10:01 UTC, srivastava21ashish requested changes

2024-04-25 10:46 UTC, vdua commented on blocks/form/components/dateField.js
> +}
Since the class doesn't have any members you can just use a single function
```
export default function decorateDateField(fieldDiv, field, htmlForm) {
      const dateField = fieldDiv.querySelector('input');
      const textInputValue = dateField.getAttribute('edit-value');
      dateField.type = 'date';
      dateField.value = textInputValue;
      const today = new Date();
      const currentDate = today.toISOString().split('T')[0];
      dateField.setAttribute('max', currentDate);
      return fieldDiv;
}
```

2024-04-25 10:46 UTC, vdua commented on blocks/form/components/dateField.js
> +}
Same thing for all the other decorators as well

2024-04-25 10:48 UTC, vdua commented on blocks/form/mappings.js
> +  if (type.includes('accordion')) {
can we use the same approach (as appliedCssClassNames) here as well.

2024-05-02 12:13 UTC, mainiaditaya approved these changes
merging it for UAT drop. We have one dom api to create element for password icon. need to check better way to do that.

2024-05-02 12:13 UTC, merged