Stepper for your details screen
aemsites/hdfc-bank pull request #19
Opened 2024-03-05 07:19 UTC by suparnabose373

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-03-05 07:57 UTC, srivastava21ashish requested changes

2024-03-05 07:57 UTC, srivastava21ashish commented on blocks/form/functions.js
> +      if (stepperLegend) {
Can this construct be changed to 1 line eg: stepperLegend?.classList?.add('your class'); 
Basically using optional chaning instead of creating 1 condition branch in code.

2024-03-05 07:57 UTC, srivastava21ashish commented on blocks/form/functions.js
> +  const ccDetailsWizard = document.querySelector('.form-corporatecardwizardview.field-wrapper.wizard');
This logic could be separate function. So code will be organised and appear to eyes like steps happening on wizardInit.
Eg: onWizardInit() {
  decoratePanels();
  someOtherFunction1();
  someOtherFunction2...
  ......
}

decoratePanels = () => {
//This code here.
}

2024-03-05 09:35 UTC, srivastava21ashish approved these changes

2024-03-06 06:48 UTC, mainiaditaya requested changes
please start using variables for wizard background, border, border right, width etc. using hdfc in naming convention to avoid naming conflicts.

2024-03-06 06:49 UTC, closed without merging