Feature 1.0/checkbox as toggle
aemsites/hdfc-bank pull request #20
Opened 2024-03-06 08:49 UTC by kunal-adobe

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-03-07 04:43 UTC, srivastava21ashish requested changes

2024-03-07 04:43 UTC, srivastava21ashish commented on blocks/form/functions.js
> +  firstname = firstname == null ? "" : firstname;
use single quotes

2024-03-07 04:43 UTC, srivastava21ashish commented on blocks/form/form.css
>  :root {
Write your CSS in styles.css and import it in forms.css. No changes directly in forms.css please. 
Also I see a lot of formatting isues.

2024-03-07 04:43 UTC, srivastava21ashish commented on blocks/form/functions.js
>   */
Execute npm run lint and fix all liniting issues, and then raise your PR

2024-03-07 04:43 UTC, srivastava21ashish commented on blocks/form/functions.js
>   */
Lint issues in file:
/home/runner/work/hdfc-bank/hdfc-bank/blocks/form/functions.js
Error:   10:35  error    Strings must use singlequote  quotes
Error:   12:33  error    Strings must use singlequote  quotes
Error:   13:27  error    Strings must use singlequote  quotes
Error:   27:48  error    Strings must use singlequote  quotes
Error:   32:39  error    Strings must use singlequote  quotes
Warning:   39:5   warning  Unexpected console statement  no-console
Error:   46:50  error    Strings must use singlequote  quotes
Error:   47:32  error    Strings must use singlequote  quotes
Error:   47:56  error    Strings must use singlequote  quotes
Warning:   49:5   warning  Unexpected console statement  no-console
Error:   50:86  error    Missing trailing comma        comma-dangle
Error:   59:47  error    Strings must use singlequote  quotes
Error:   71:5   error    Strings must use singlequote  quotes
Error:   72:5   error    Strings must use singlequote  quotes
Error:   72:38  error    Missing trailing comma        comma-dangle

2024-03-11 06:23 UTC, mainiaditaya requested changes
add URL for testing

https://develop--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc
2. discussed the fix for the async function call. kindly add the same.

2024-03-11 06:23 UTC, mainiaditaya commented
reverted for the async function fix.

2024-03-11 06:29 UTC, closed without merging