Stage test2
aemsites/hdfc-bank pull request #293
Opened 2024-07-23 13:19 UTC by BazilMuralidharan

URL for testing:

- https://stage-test2--hdfc-bank--aemsites.hlx.live/content/forms/af/hdfc_haf/cards/corporatecreditcard/uat/hdfc?leadId=679110803&mode=dev

2024-07-25 14:50 UTC, ravise5 commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +    if (emailValid) {
`emailValid === true` would be a better check.

2024-07-25 14:52 UTC, ravise5 commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +        dobDefFieldDesc.style.display = 'none';
Why are we using the DOM APis to hide the field description here?

2024-07-25 14:53 UTC, ravise5 commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +  cardImg.innerHTML += `<span class='cardNameText'>${name}</span>`;
Can this be done via `globals`?

2024-07-25 14:55 UTC, ravise5 requested changes
Please check the comments above.

2024-07-26 06:45 UTC, mainiaditaya commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +  cardImg.innerHTML += `<span class='cardNameText'>${name}</span>`;
@ravise5 this is the name shown on the image dynamically, when the name is selected from Dropdown. we can show it w/o dom on the image by using another static text field and using css , place that field on the image to look like name on card. kindly advise if we can should use additional field in this case.

2024-07-26 06:45 UTC, mainiaditaya commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +    if (emailValid) {
@ravise5  changed

2024-07-26 06:47 UTC, ravise5 commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +  cardImg.innerHTML += `<span class='cardNameText'>${name}</span>`;
This would be the recommended approach here

2024-07-26 14:40 UTC, ravise5 commented
@BazilMuralidharan there is some linting issue in `accordion.css`. Can you fix that to make build pass?

2024-07-29 05:09 UTC, mainiaditaya commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +  cardImg.innerHTML += `<span class='cardNameText'>${name}</span>`;
this is done and ready for review

2024-07-29 05:49 UTC, ujjwal5 commented on head.html
> +<link rel="canonical" href="https://stage-test2--hdfc-bank--aemsites.hlx.live/content/forms/af/hdfc_haf/cards/corporatecreditcard/uat/hdfc" />
are we planning to change this with every pr we raise and finally move to main ?

2024-07-29 05:58 UTC, BazilMuralidharan commented
> @BazilMuralidharan there is some linting issue in `accordion.css`. Can you fix that to make build pass?

Lint issue in accordian-page.css is fixed.

2024-07-29 07:13 UTC, ravise5 commented on creditcards/corporate-creditcard/corporate-creditcardFunctions.js
> +        dobDefFieldDesc.style.display = 'none';
https://github.com/aemsites/hdfc-bank/pull/299
Please merge this PR I have removed the dom APIs and test the usecase once 
cc: @mainiaditaya  @BazilMuralidharan

2024-07-29 08:51 UTC, mainiaditaya commented on head.html
> +<link rel="canonical" href="https://stage-test2--hdfc-bank--aemsites.hlx.live/content/forms/af/hdfc_haf/cards/corporatecreditcard/uat/hdfc" />
this will be changed at least one more time before CUG. We have asked HDFC for exact keywords from marketing team and for final short URL as well. For now this is added to fix and SEO LHS and overall LHS.

2024-07-29 08:58 UTC, ravise5 approved these changes
LGTM

2024-07-29 09:09 UTC, ravise5 approved these changes

2024-07-29 12:32 UTC, ujjwal5 approved these changes

2024-08-01 06:43 UTC, merged