Feature 1.0/accordion
aemsites/hdfc-bank pull request #34
Opened 2024-03-15 07:05 UTC by suparnabose373

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-03-15 12:03 UTC, srivastava21ashish requested changes

2024-03-15 12:03 UTC, srivastava21ashish commented on blocks/form/components/accordion.js
> +          legend.classList.add('hdfc-accordion-style');
optional chaining

2024-03-15 12:27 UTC, suparnabose373 commented on blocks/form/components/accordion.js
> +          legend.classList.add('hdfc-accordion-style');
done

2024-03-18 04:52 UTC, kjaiswal-woolworths commented on blocks/form/components/accordion.js
Can we do panel check before adding class? It may give error if panel is not available. Also can we add js doc for this.

2024-03-18 04:53 UTC, kjaiswal-woolworths commented on blocks/form/styles.css
> +  background-color: var(--background-color-primary);
use proper naming convention for colors.

2024-03-18 05:23 UTC, kjaiswal-woolworths approved these changes

2024-03-18 05:36 UTC, kjaiswal-woolworths approved these changes

2024-03-18 05:37 UTC, kunal-adobe approved these changes

2024-03-18 06:56 UTC, satyajeetdhere7444 commented on styles/typography.css
In this file we are maintain only font related settings.

2024-03-18 07:01 UTC, srivastava21ashish approved these changes

2024-03-18 07:01 UTC, satyajeetdhere7444 approved these changes

2024-03-18 07:01 UTC, merged