navigation from check offer to comfirm card view with CheckOffer dumm…
aemsites/hdfc-bank pull request #50
Opened 2024-03-18 13:04 UTC by BazilMuralidharan

URL for testing

- https://feature-ccWizardNavigation--hdfc-bank--aemsites.hlx.page/content/forms/af/hdfc

2024-03-18 13:11 UTC, kunal-adobe approved these changes

2024-03-19 05:48 UTC, srivastava21ashish requested changes

2024-03-19 05:48 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +    jsonObj.requestString.mobileNumber = String(mobileNo) ?? '';
This condition is not at all required. At API payload mobile No is mandatory otherwise its error case

2024-03-19 05:48 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +  const navigateFrom = document.getElementsByName('corporateCardWizardView')[0];
optional chaining document.getElementsByName('corporateCardWizardView')?.[0]

2024-03-19 05:48 UTC, srivastava21ashish commented on creditcards/corporate-creditcardFunctions.js
> +  const current = navigateFrom.querySelector('.current-wizard-step');
optional chaining wherever applicable please

2024-03-22 12:04 UTC, BazilMuralidharan commented on creditcards/corporate-creditcardFunctions.js
> +    jsonObj.requestString.mobileNumber = String(mobileNo) ?? '';
Since Mobile is mandatory. Hence nullish (condition) removed for all the payloads using having mobileNumber.

2024-03-22 12:06 UTC, BazilMuralidharan commented on creditcards/corporate-creditcardFunctions.js
> +  const current = navigateFrom.querySelector('.current-wizard-step');
optional chaining added and moveCCWizardview function modified.

2024-03-22 12:06 UTC, BazilMuralidharan commented on creditcards/corporate-creditcardFunctions.js
> +  const navigateFrom = document.getElementsByName('corporateCardWizardView')[0];
optional chaining added and moveCCWizardview function modified.

2024-03-26 04:17 UTC, mainiaditaya approved these changes

2024-03-26 04:17 UTC, merged