create error page
aemsites/hdfc-bank pull request #606
Opened 2024-10-15 12:29 UTC by findvinu

Add CSS for the wrong mobile number error page and the error page that appears after three incorrect entries. Additionally, implement a new function to add a class to the body based on the API response.

Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #<gh-issue-id>

Test URLs:
- Before: https://main--{repo}--{owner}.hlx.live/
- After: https://<branch>--{repo}--{owner}.hlx.live/

2024-10-15 14:29 UTC, srivastava21ashish requested changes

2024-10-16 04:35 UTC, findvinu commented on styles/nre-nro.css
> +    .form form .field-wrapper .button-wrapper.field-submitotp{
The parent nre class has already been used.
![image](https://github.com/user-attachments/assets/274d9e27-ff03-47e2-a3c4-4536c9c5fb82)

2024-10-16 04:37 UTC, findvinu commented on liabilities/nre-Nro/nre-nroFunctions.js
> +    document.body.classList.add('errorPageBody');
We will add the class based on the API response without directly manipulating the DOM. This function will be implemented on the AEM side, and we’ll retrieve the current page name parameter. Mintu and Vaibhav will assist with implementing this headless functionality.

2024-10-16 06:56 UTC, roym1234 approved these changes

2024-10-16 06:57 UTC, merged